#!/bin/bash

ARG="$1"
if [ "$ARG" == "install" ]; then

    mkdir -p ~/.local/bin
    cp -r ./vs-cat ~/.local/bin/
    chmod +x ~/.local/bin/vs-cat/vscat
    chmod +x ~/.local/bin/vs-cat/vscat.py
    ln -sf ~/.local/bin/vs-cat/vscat ~/.local/bin/vscat
    

else 
    python3 vscat.py $ARG
fi